//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wucefus.TestApp.SoapConsents {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDto", Namespace="http://schemas.datacontract.org/2004/07/Wucefus.Core.Dto")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wucefus.TestApp.SoapConsents.GetConsentsResultDto))]
    public partial class ResponseDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOk {
            get {
                return this.IsOkField;
            }
            set {
                if ((this.IsOkField.Equals(value) != true)) {
                    this.IsOkField = value;
                    this.RaisePropertyChanged("IsOk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessTime {
            get {
                return this.ProcessTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessTimeField, value) != true)) {
                    this.ProcessTimeField = value;
                    this.RaisePropertyChanged("ProcessTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetConsentsResultDto", Namespace="http://schemas.datacontract.org/2004/07/Wucefus.Core.Dto")]
    [System.SerializableAttribute()]
    public partial class GetConsentsResultDto : Wucefus.TestApp.SoapConsents.ResponseDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wucefus.TestApp.SoapConsents.ConsentDto[] ConsentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wucefus.TestApp.SoapConsents.ConsentDto[] Consents {
            get {
                return this.ConsentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsentsField, value) != true)) {
                    this.ConsentsField = value;
                    this.RaisePropertyChanged("Consents");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsentDto", Namespace="http://schemas.datacontract.org/2004/07/Wucefus.Core.Dto")]
    [System.SerializableAttribute()]
    public partial class ConsentDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SoapConsents.IConsents")]
    public interface IConsents {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsents/Ping", ReplyAction="http://tempuri.org/IConsents/PingResponse")]
        string Ping(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsents/Ping", ReplyAction="http://tempuri.org/IConsents/PingResponse")]
        System.Threading.Tasks.Task<string> PingAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsents/GetConsentsAll", ReplyAction="http://tempuri.org/IConsents/GetConsentsAllResponse")]
        Wucefus.TestApp.SoapConsents.GetConsentsResultDto GetConsentsAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsents/GetConsentsAll", ReplyAction="http://tempuri.org/IConsents/GetConsentsAllResponse")]
        System.Threading.Tasks.Task<Wucefus.TestApp.SoapConsents.GetConsentsResultDto> GetConsentsAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConsentsChannel : Wucefus.TestApp.SoapConsents.IConsents, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsentsClient : System.ServiceModel.ClientBase<Wucefus.TestApp.SoapConsents.IConsents>, Wucefus.TestApp.SoapConsents.IConsents {
        
        public ConsentsClient() {
        }
        
        public ConsentsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsentsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsentsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsentsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Ping(int value) {
            return base.Channel.Ping(value);
        }
        
        public System.Threading.Tasks.Task<string> PingAsync(int value) {
            return base.Channel.PingAsync(value);
        }
        
        public Wucefus.TestApp.SoapConsents.GetConsentsResultDto GetConsentsAll() {
            return base.Channel.GetConsentsAll();
        }
        
        public System.Threading.Tasks.Task<Wucefus.TestApp.SoapConsents.GetConsentsResultDto> GetConsentsAllAsync() {
            return base.Channel.GetConsentsAllAsync();
        }
    }
}
